### ISSUE TITLE
Frontend Framework 

### ISSUE THREAD

**Issue by Marius998** [Marius998/All-for-One-Rentals#1]
Framework ja oder nein ? 
Falls ja , welches ?

**Comment by Marius998** [comment]
Vue.js 
https://vuejs.org/v2/guide/


Vue CLI 
https://cli.vuejs.org/


Google für Vue 
https://www.npmjs.com/package/vue2-google-maps

https://alligator.io/vuejs/vue-google-maps/

**Comment by Felix2019** [comment]
Frontend Framework
https://vuetifyjs.com/en/

**Comment by CCB-Git** [comment]
Vue wurde als Framework gewählt, da es Teilen unseres Teams schon gut bekannt war und zur Entwicklung von Single Page Applications, wie wir sie entwickeln möchten, vorgesehen ist.
Weitere wichtige Faktoren bei der Wahl war die gute Dokumentation und das Vue im Gegensatz zu Angular (TypeScript) oder react (JSX) keine weiteren Sprachen neben JavaScript, HTML und CSS benötigt.
