### ISSUE TITLE
Anbieter

### ISSUE THREAD

**Issue by Marius998** [Marius998/All-for-One-Rentals#3]
Welche Anbierter  ( mit API )

**Comment by Marius998** [comment]
KVB / Nextbike 
https://open.nrw/dataset/standorte-fahrradverleih-koeln-kvb-rad-k
http://api.nextbike.net/maps/nextbike-official.xml?city=14

**Comment by Marius998** [comment]
Lime Go / _komische Api_
https://lime-go.readme.io/docs/feed

**Comment by CCB-Git** [comment]
> Lime Go / _komische Api_
> https://lime-go.readme.io/docs/feed

Kann daran liegen, dass es nicht die der Lime Scooter ist 😂

Eine gute Doku der richtigen Lime API findet sich hier: https://github.com/ubahnverleih/WoBike/blob/master/Lime.md#send-back-otp-code

**Comment by Felix2019** [comment]
Alle Anbieter implementiert, die geplant waren!
